### ISSUE TITLE
Stops slack from working

### ISSUE THREAD

**Issue by mnlyjkn** [scryfall/feedback#100]
I tried using scryfall to post two different cards in the same message and it caused slack to stop working.  This is the second time this has happened.  I cannot open slack until the posted message leaves the screen from other messages moving it.  If I try to scroll to the message, slack stops.  The first time somebody else posted two cards in the same message and I didn't realize that was what caused slack to stop working.

**Comment by csuhta** [comment]
Can you elaborate a bit? Are you talking about pasting in links like `https://scryfall.com/card/cmd/172` into Slack? 

Can you provide a screenshot of what it looks like before or after the problem?

**Comment by mnlyjkn** [comment]
The message I was typing used the [[cardname]] to post the image and text of the card in Slack.  I used it twice in the same message before hitting send. The error box then appeared from Slack saying "Unfortunately, Slack has stopped."  with the option to report or hit okay.  The two cards I was using were [[Triskaidekaphobia]] and [[Tree of Perdition]].  Slack has only stopped one other time since Scryfall was added to Slack, but I never figured out why since somebody else had posted a message using it.  Every other time Scryfall was used only once in a message with no issues.  I cannot get a screenshot.

 

 

 

-----Original Message-----

**Comment by csuhta** [comment]
Ok, this seems to be a problem with the Slack app itself, and we won't be able to fix it here.

When you use `[[card names]]` in messages, our bot posts a new message in that channel with attachments. This should not cause the Slack app to freeze or hang or crash on your phone, since it's just a new message.

Please report this problem to Slack, by going to the Slack app's settings on your phone and selecting "Send Feedback" or visiting https://slack.com/help/contact and submitting a request online.

Feel free to also give the Slack support person a link to this GitHub issue.
