### ISSUE TITLE
Syntax to search by exact mana cost

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#108]
[/u/Piogre on Reddit](https://www.reddit.com/r/magicTCG/comments/6gsf5i/mtgcardfetcher_linked_sites/disvkx8/?context=3):

> in particular, the "mana=" syntax, which on magiccards gives you only cards with the [equivalent mana cost](http://magiccards.info/query?q=mana%3Duwg+e%3Ac13&v=card&s=cname), and on scryfall gives you [everything that it's a subset of](https://scryfall.com/search?q=e%3Ac13+mana%3Duwg) - a quick way for me to look up the name of a (foreign) card I don't know when sorting is to search the edition and mana cost, and if the card has a mana cost of, say, R, that can be a problem with scryfall's method.

[/u/Xelazeratul on Reddit](https://www.reddit.com/r/magicTCG/comments/6gsf5i/mtgcardfetcher_linked_sites/diswyvf/?context=3)

> To clarify, this is often used when trying to find the english name of a card when one has the foreign card in hand. Mana cost and edition don't change on foreign cards.

Piogre brought this up in the context of _different_ syntax from magiccards.info, but unless I'm missing something this is just _missing_ syntax from Scryfall.

**Comment by gmac** [comment]
Exact mana cost can be searched using `m:{U}{U}{3} cmc=5`. What else needs to happen here?

**Comment by gmac** [comment]
I've updated the advanced search form to note how exact mana searches work.

<img width="779" alt="screen shot 2017-06-23 at 9 26 05 am" src="https://user-images.githubusercontent.com/727224/27484139-22310a48-57f6-11e7-9cca-c4c6ebf959c0.png">

**Comment by NilsEnevoldsen** [comment]
Yes, I overlooked this. I think that does it.

**Comment by doppeldeveloper** [comment]
I should point out the `m:stuff cmc=stuff` method sorta fails on `{X}` cards. For example, [`m:{R}{G} cmc=2`](https://scryfall.com/search?q=m%3A%7BR%7D%7BG%7D+cmc%3D2) finds Apocalypse Hydra, which doesn't have an exact cost of `{R}{G}` and would never be cast for only 2 mana. This is more relevant at low mana costs: if I'm trying to find a card I can cast on turn 1 in my green deck, [these cards don't fit](https://scryfall.com/search?q=m%3A%7BG%7D+cmc%3D1+%28m%3A%7BX%7D%29).

This may be more or less impactful or even effectively a "feature" since I'm not aware of all the use cases for this feature.
