### ISSUE TITLE
Persist all form elements when navigating back to advanced search page

### ISSUE THREAD

**Issue by chuckharmston** [scryfall/feedback#12]
From /u/Back_Alley_G [on Reddit](https://www.reddit.com/r/magicTCG/comments/6637j9/amonket_searchable_on_scryfall_lovingly/dgfe77d/):

> Scryfall has been very useful and awesome with all the options of the advanced searching. I only wish there was a way to save your search details so once you click back to the your advanced search page used for the search all of the boxes you had checked are still checked. Text still remains in the boxes but I always have to recheck all the various boxes I marked. I thought this used to be an option but maybe not.

**Comment by csuhta** [comment]
I can’t reproduce this problem in Safari, Firefox, or Chrome. Is it a mobile issue? Any other info?

**Comment by chuckharmston** [comment]
I can in all three.

*STR:*
1. Search for `c:w`, using the advanced search page (i.e. checking the checkbox).
2. Submit.
3. Hit the browser back button.

*Expected:* the same checkbox is checked.
*Actual:* no checkboxes are checked.

**Comment by gmac** [comment]
I think the point is that you didn't used to be limited to just the back button. You could search, click around, navigate back, and still be able to have your last search persisted (there was a checkbox that allowed you to "remember my search" which re-populated from localStorage). In the new form, you can only use the back button to get back to your last search.

**Comment by csuhta** [comment]
@chuckharmston I can't reproduce with those steps either. I even tried ticking all checkboxes and all of them are fine when using the back button.

**Comment by gmac** [comment]
I'll put a PR together that proposes the old behavior. It's pretty inoffensive, and very handy for doing repeat search and browse ops.

**Comment by csuhta** [comment]
@gmac I'm fine with the browser behavior here, we should rely on it since it's built-in. It gives us more agility when changing the form too

**Comment by csuhta** [comment]
Looking into this more: It's either a problem caused by a browser plugin (some versions of 1Password, for example), or it's Microsoft Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4525797/

Microsoft is aware of the problem. We shouldn't try to patch Edge or any possible browser plugins with JavaScript. Just wait for them to roll out fixes themselves.

**Comment by gmac** [comment]
`... I thought this used to be an option but maybe not.`

This user was specifically referring to old behavior of the advanced search form, where a "remember search" checkbox would cache their search configuration and repopulate it for them when they returned to the advanced search page, regardless of how much browsing they did between using the form and exploring subsequent search results. Personally, I found this feature useful as well because you could configure a complex advanced search query, browse around with it, and then later return to the advanced search page and make small adjustments to your last query.

So, I advocate for the value in this – which is fundamentally oriented towards empowering users the best and most convenient search experience possible.
