### ISSUE TITLE
Elves vs. Goblins duel decks have wrong set code

### ISSUE THREAD

**Issue by ClintTCG** [scryfall/feedback#128]
Currently:
EVG = Duel Decks Anthology: Elves vs. Goblins
DD1 = Duel Decks: Elves vs. Goblins	

Should be 
EVG = Duel Decks: Elves vs. Goblins
DD3EVG = Duel Decks Anthology: Elves vs. Goblins

The set code for Duel Decks: Elves vs. Goblins should be EVG
source: http://mtg.gamepedia.com/Duel_Decks:_Elves_vs._Goblins

The set code for  **all** Duel Decks Anthology sets should prefix with DD3
source: http://magic.wizards.com/en/content/duel-decks-duel-decks-anthology

For the other Duel Deck Anthology sets broken out into pieces, ScryFall has non-official set codes for all of them, which is fine, but the fact that one of them overlaps with an official set code makes coding around this issue easy to miss.

**Comment by csuhta** [comment]
The situation with DD3 is not ideal, but here's the rationale:

- The Duel Decks Anthology cards are broken into distinct sets on Gatherer.
- The actual cards for Duel Decks Anthology: Elves vs. Goblins have `EVG` written on them. The other decks have their own respective set codes written on them.
- Because of the two things above, we made four distinct `DVD`, `EVG`, `GVL`, `JVC` codes for Duel Decks Anthology.
- The prefix setup like `DD3_EVG` or `DD3-EVG` is something MTGJSON invented, and we didn't copy that style.

<img width="162" alt="r9mnzexm" src="https://user-images.githubusercontent.com/769083/27451969-e7f527d4-575e-11e7-8eef-2e7e8fef5319.png">

Technically we should have two sets with an `EVG` set code, but we don't duplicate set codes in our database. So we set the original Elves vs. Goblins deck to `DD1` because:

1. they don't have a code on the bottom of the card and 
2. the following Duel Deck set (Jace vs Chandra) had the code `DD2`.

**Comment by ClintTCG** [comment]
Thank you for the for the detailed and thoughtful reply!

It's definitely awkward, because that 3-letter code isn't just about what's printed on the card, but it also is shared within the larger group at Hasbro.  

Even though the original duel deck lacks the EVG lettering at the bottom, WotC still uses that as the official set code for that product: http://magic.wizards.com/en/content/duel-decks-elves-vs-goblins

Sets like the International Collector's Edition lack an official Hasbro-defined set code, but when we do have an official code, it feels like it should be utilized for proper interfacing with everyone else who uses those same codes.  

As far as offering the idea of the prefix, that suggestion was based more on your current way of doing things with adding a prefix / suffix for sub-sets within a single larger set.  I.E., Thros Promos being "PTHS", I thought that EVG within Duel Decks Anthology would nicely slot into that paradigm as either "DD3EVG" or "EVGDD3" -- I really wanted to keep it in line with your existing paradigms.  

Either way, thanks for the discussion!  I appreciate it! :)

**Comment by ClintTCG** [comment]
Just discovered something interesting -- Wizards uses the syntax of underscore-prefix on their naming for these set symbols:

http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=DD3_EVG&size=large&rarity=R

http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=EVG&size=large&rarity=R

Not sure if that flows into your decision at all, but I thought you might find it interesting to know that it wasn't just a convention that was created by mtgjson.

**Comment by gmac** [comment]
Assigning this to Corey to make the final call here.

**Comment by csuhta** [comment]
We're not going to change anything for now, because of the reasons I listed in https://github.com/scryfall/feedback/issues/128#issuecomment-310479457 

It would be more of a concern if we had the wrong code for a expansion/draftable set, but the fact that we have both Elves vs. Goblins supplemental products indexed at all is the most important part.
