### ISSUE TITLE
Search by number of colors

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#211]
Just a QOL improvement.

Proposed syntax: one or more of `c:4`, `c:four`, `c:4color`, `c:fourcolor`. Symmetrical syntax for 0, 1, 2, 3, 4, 5.

Syntax like `c:4` is simplest, causes no collisions with other color abbreviations (`c:foUr`), and can be combined (`c:4u`). I favor it.

Additional possibilities: `c:monocolor`, `c:ally`, `c:enemy`, `c:wedge`, `c:shard`.

Easy to implement, but also not commonly useful, so I understand if you decide to wontfix.

**Comment by doppeldeveloper** [comment]
I'm conscious of a use case for this, which is improve color & faction-identity balance in a deck. I already have the tools to do this in Scryfall, but this is an alternate route to doing that.

A recent Temur commander deck I made skewed ~75% green. This was fine for that deck. I then moved on to make a Mardu colored [Queen Marchesa](https://scryfall.com/card/cn2/78) deck, and it skewed toward white and white-black *without* much inclusion of red in anything. This wasn't so good: I need more representation of red-black and red-white in that deck, and *particularly* needed representation of red-white because Boros cards have the effects and aesthetics I want for that deck. (Red monocolor wasn't so important.)

For that deck, I could search [`ci:rwb c:rw`](https://scryfall.com/search?q=ci%3Arwb+c%3Arw) for cards  that are at least red-white within the Mardu color identity. I could also search [`ci:rwb ci:rm`](https://scryfall.com/search?q=ci%3Arwb+c%3Arm) which finds me red multicolor cards within that identity. I can also use [`c:rwb -c:ug`](https://scryfall.com/search?q=c%3Agur+-c%3Awb) to find cards that are strictly Mardu 3-color, and once issue #1 gets implemented I'll be able to search `c!rwb` instead.

With this feature, I could run this search: `ci:rwb c:2 c:r`. It's a different way of conveying my thoughts to the search: "I want cards within Mardu that are 2 colors and one of them is red." It might just take out some mental steps sometimes between "... and how do I search for that exactly?" and arriving at the equivalent syntax (`ci:rwb c:rm`, etc).

**Comment by doppeldeveloper** [comment]
[Ramos, Dragon Engine](https://scryfall.com/card/c17/55) just added another use benefit for this, specifically the use case of finding **3-color spells** since there seems to be a gap for those.

I can find five-color cards easily enough by just searching [`c:wubrg`](https://scryfall.com/search?q=c%3Awubrg).

I can't easily search for four-color cards, but AFAIK there's only [eleven four-color cards in the game](https://scryfall.com/search?q=%28c%3Aubrg+or+c%3Awbrg+or+c%3Awurg+or+c%3Awubg+or+c%3Awubr%29+cmc%3C%3D4) and I already know what those are: the Nephilim, the C16 commanders, and Transguild Courier, so that's not really an issue.

However there's nothing really to search for three-color cards: I can find all the multicolor ones (`c:m`) but there's an *awful lot* more two-color cards than three-color cards, so I just have to sift through those manually.

Finding cards that are at least two-color is easy enough (`c:m`) and exactly one-color (`-c:m -c:c`) or no-color (`c:c`).

**Comment by doppeldeveloper** [comment]
Related real world request: https://boardgames.stackexchange.com/questions/34516/commanders-with-at-least-four-colors-in-their-color-identity 

Someone was searching for a way to find commanders with at least four colours in their color identity. This wasn't asked by me or anyone I know.

**Comment by csuhta** [comment]
You can now search by color cardinality! https://scryfall.com/changelog/improvements-to-color-color-identity-operators-138
