### ISSUE TITLE
When I hit "transform" on a double-faced card, change the dataset next to it.

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#234]
Below [Accursed Witch](https://scryfall.com/card/soi/97a) there's a "transform" button that swaps the image around.

When I hit "transform" the data should also swap around to show the other side's data: the stat block should be swapped out for [Infectious Curse](https://scryfall.com/card/soi/97b)'s stat block, the card ID in the top right (the "#97a" underneath the set heading) should swap over to Infectious Curse's stat block, and the highlighted entry in the "Faces, tokens, & other parts" sidebar should change.

The same should occur for meld cards (e.g. [Bruna, the Fading Light](https://scryfall.com/card/emn/15a)) with the meld button for the back face (Brisela) replaced by an "unmeld" button which returns me to the card I was originally viewing. That means if I visit Bruna's page, I'd get a Meld/Unmeld button that would toggle back and forth between Bruna's data and Brisela's data; if I visited Gisela's page, it would toggle back and forth between Gisela and Brisela.

(If we implement #40, the transform paragraph may have no place as a feature, but the meld paragraph would apply to swapping back and forth between Bruna/Gisela and Brisela.)

This is effectively like a single-page-application kinda thing, or an AJAX-y kinda thing, although a card display page that's showing a transform card could just grab that information ahead of time.

**Comment by gmac** [comment]
This is taking the transform button down a rabbit hole that we don't want to follow... that button is really only provided as a convenience for inspecting what would be the physical printed media. I do agree that flipping the card makes the page a little confusing once the image and page text don't line up. The solution that I've considered in the past would be to make the backside artwork grayscale so that it feels like isolated content rather than part of the page.

Otherwise, we provide links to the related faces in the "Faces, Tokens & Other Parts" module. There are no plans to further integrate transform card sides.

**Comment by csuhta** [comment]
We're planning to eventually merge the transform cards into a single page/record like we've done with the split spells and flip creatures, so hopefully that will alleviate this issue.
