### ISSUE TITLE
Suggestion: remove the option to download card image

### ISSUE THREAD

**Issue by MickHardins** [scryfall/feedback#260]
Hi! I suggest you to remove the options to download card images from your website. Don't get me wrong: i really love it, but mtgimage.com was shutted down using images' download links as excuse, and i really don't want this to happen again. 
By removing links, users would still be able to download images, as they are on gatherer site, and you'll minimize the risks! 😃

**Comment by doppeldeveloper** [comment]
Scryfall probably does not have to worry about this. (I'm not a representative or team member, just an interested user.)

I googled the mtgimage name and the first hit was [this reddit thread](https://www.reddit.com/r/magicTCG/comments/2yl94g/mtgimagecom_has_been_shut_down_by_wizards/), with the top reply being:

> Just to try and clarify and provide some reason. It seems that mtgimage was taken down because its sole purpose was to host card and symbol images, whereas sites like magiccards.info and TCGPlayer also have information about the cards and other text (such as price info and format legality) that extend beyond just hosting a card image. Also, being able to download entire sets of card images in one ZIP file wouldn't make WOTC too happy as that's definitely redistribution of property. In fact, that was possibly the biggest problem.

It should be noted that Magiccards.info, Tappedout.net, Mtgvault, and other sites which feature a card database and host their own card images have been around basically forever and haven't been shut down. The large redistributors also host images and (evidently) haven't been made to stop. Since Scryfall is in the category of sites which historically are just fine, it is also probably just fine.

**Comment by silasary** [comment]
In addition to that, the download button is a mere convenience. If someone wanted to download all the images, they could still get the images from the API or img tags.

As long as the Scryfall team doesn't start offering context-free bulk downloads of images, I doubt they'll fall afoul of Hasbro's lawyers.

**Comment by csuhta** [comment]
Closing for the reasons above. The concern was very much appreciated though, @MickHardins
