### ISSUE TITLE
Include frame data for Game Day Promos

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#266]
Game Day Promo cards (like [Immolating Glare](https://scryfall.com/card/pogw/20), [Walk the Plank](https://scryfall.com/card/pxln/130), and [Kiora's Follower](https://scryfall.com/card/pbng/150)) are listed as Frame=2015.  

This should really be a separate entry. (I don't know what to call it though)

**Comment by gmac** [comment]
Those cards still use the basic frame format of their respective sets, and are each correctly flagged as such. The unique characteristic that I think you're calling out is their extended art frame, which we track in Scryfall as a field called `full_art`. Looking through API docs and card JSON data, it doesn't look like we actually publish that value at the moment. We'll consider where and how to surface that data.

**Comment by gmac** [comment]
Ha, as it turns out, full art has always been searchable but was never officially documented. You can check it out using `is:full`, https://scryfall.com/search?q=is%3Afull. Docs have been updated: https://scryfall.com/docs/reference#frame.

Also, I've added the `full_art` field into card JSON data.

Good catch here, thanks for the report!
