### ISSUE TITLE
Include user ratings

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#29]
Users could vote on cards.

 - This would require some kind of account to prevent abuse
    - You could require Facebook accounts to prevent abuse
 - Card ratings should be exposed to search
 - Card ratings should be exposed to sort
 - You would need to decide:
   - What rating to display on the card
   - What rating to sort by
   - What rating to search by
   - [Evan Miller](http://www.evanmiller.org/ranking-items-with-star-ratings.html) can help with these
 - You could mirror Gatherer by making it a five-star rating scale
 - I always disliked how different printings got different ratings in Gatherer, as it resets to zero for new printings. You would have to make a judgment call about whether to do that. (Except basic lands, where art/frame is obviously the only consideration.)
 - You could jump-start the ratings by importing Gatherer ratings
    - Depending on the algorithm used, this might require assumptions about the distribution of individual votes on each card. (e.g. assume the continuous uniform distribution with the appropriate mean and the largest possible support.)

**Comment by doppeldeveloper** [comment]
If there's a rating system I don't think it should be a single amalgamated star rating. Those have never been very useful or meaningful to me. Here's what goes on for me:

* If I see a card with a high star rating, is that because it's powerful or because many people just sorta *like* it? If it's a low star rating, does that mean it's ineffective or sucks somehow, or do people just hate seeing it?
* What does it mean that on Gatherer, [Spellshock](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=397489) is rated 5 and [Staggershock](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=193571) is rated 4, but [Cyclonic Rift](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=270798) is rated 4 and [Blood Moon](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=370419) is rated 4? (But, Blood Moon and Cyclonic Rift are rated 5 if I pick the right edition, based on unknown voting data.)
* What does it mean that [Snakeform](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=157401) and [Beast Within](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=373352) both have a rating of 4?
* What's it mean that [these cards from Commander 2016 have a rating below 3](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&rating=+%3C[3]&set=+[%22Commander%202016%22])? Exotic Orchard has a rating of 2.9 and it's an *awesome* card for Commander.

I've never gotten any use out of star ratings because I don't really know what I should be reading out of them. They don't tell me whether the card's better or worse for my deck. I can't reliably filter out the absolute worst cards because maybe they're just worse *for other people*.

It's worth bearing in mind that when Wizards surveys peoples' feelings on cards, they ask them to rate cards on multiple factors. My vague memory is they ask people to separately rate image, function, flavor text, and overall impression, each on a scale of 1-5. However then we reach things like *Miracle* cards: when Maro wrote his [Storm Scale: Innistrad and Shadows over Innistrad](http://magic.wizards.com/en/articles/archive/making-magic/storm-scale-innistrad-and-shadows-over-innistrad-2017-03-27) article, he noted:

> Miracles are pretty polarizing. The players who like them really like them, and the players who hate them really hate them. Overall, it ranks just a little below average.

So if we have a massive polarized love/hate relationship on a certain card, I'd at least prefer to see how may people voted what, because 100 5-star ratings and 100 1-star ratings is more informative to me than the rating that would average out to: 3. (One tells me loads of people think that card is the bees knees and loads of people think it's garbage, the other tells me people overall think it's average and unremarkable.)

**Comment by chuckharmston** [comment]
I am going to close this issue. As has been noted, star ratings are not particularly helpful in a vacuum. Any possible relevancy/playability score we come up with—something that is absolutely on our radar—will likely be a composite measure of popularity/usage in decks/cost.
