### ISSUE TITLE
Question about art crop usage

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#316]
> As this image is the first where we don’t include the copyright line and artist credit, you are *heavily encouraged* to show a copyright, disclaimer, and artist credit wherever you display this image.

Firstly, what kind of disclaimer do you have in mind?

Secondly - and much more messy - The artwork in *Limited Edition* was actually copyright of the artists directly, and WotC paid royalties on the artworks.

While WotC did buy the rights for some of these works, there are (AFAIK) still some cards copyright the original artist, not WotC.

Unfortunately, I can't seem to find any concrete details for which cards are still licensed, and which have been purchased.

For now, I'll just credit copyright to the artist for all LEA/LEB artworks (as per card text), but it would be lovely if this could be researched properly by someone and eventually exposed via API.

**Comment by csuhta** [comment]
> Firstly, what kind of disclaimer do you have in mind?

Something like in our footer: _The literal and graphical information presented on this site about Magic: The Gathering, including card images, the mana symbols, and Oracle text, is copyright Wizards of the Coast, LLC, a subsidiary of Hasbro, Inc. This website is not produced by, endorsed by, supported by, or affiliated with Wizards of the Coast._

When I wrote the changlog entry, I was probably being too harsh. I was mostly trying to say that if you use the art crop, you should only use it in conjunction with providing other Magic-related features and you should attempt to credit the artist and WOTC as the source of that image where it's appropriate in your UI (because the art crop doesn't conveniently have the copyright and artist as part of the picture)

> Secondly - and much more messy [...]

Are you imagining some kind of `artist_licensing` boolean or other field here to indicate when a card is copyright the artist and not WOTC?

**Comment by csuhta** [comment]
I've added additional image guidelines, we're probably going to punt on the artist nuance for now. https://scryfall.com/docs/api/images
