### ISSUE TITLE
MTGO PRM promo set missing

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#35]
I don't know the precise extent of it, but many MTGO promos are missing. Examples:

 - https://www.cardhoarder.com/cards/62531/prm-candelabra-of-tawnos
 - https://www.cardhoarder.com/cards/62485/prm-contagion
 - https://www.cardhoarder.com/cards/62449/prm-hoodwink
 - https://www.cardhoarder.com/cards/62421/prm-erratic-portal

**Comment by csuhta** [comment]
We're working on this, but its very slow-going. 

The PRM set is basically one huge slagheap for all promos on MTGO, and it's been difficult getting accurate data for this set. Our TIX vendors report the PRM set to us, but the computer-readable data they provide doesn't let us disambiguate individual prints. 

For example, there are  10+ cards named `Plains` in PRM and 3+ cards named `Path to Exile`. The data we have doesn't include the artist, which would help automate importing it and distinguishing prints from each other).

If you know a better way acquire data for this set, or you can extract from MTGO itself, it would be very helpful.

**Comment by Sniffnoy** [comment]
Thanks for this!  Just a comment, I just want to point out a few particular online promo cards which are noteworthy because, as best I can tell, their online promos are their *only* online printings.  Don't know how useful this is to you, but just in case it is, here they are.

Zodiac Dog
Zodiac Goat
Zodiac Horse
Zodiac Ox
Zodiac Pig
Zodiac Rabbit
Zodiac Rat
Zodiac Rooster
Zodiac Snake
Zodiac Tiger
Nalathni Dragon
Sewers of Estark
Windseeker Centaur
Mind Warp
Aisling Leprechaun
Headless Horseman
Abu Ja'far

(It is possible that there are others that I missed, but these are all that I could find.)

**Comment by csuhta** [comment]
https://scryfall.com/sets/prm 🎉
