### ISSUE TITLE
Combine transform and meld cards into singular pages

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#40]
Consider combining double-face cards and meld cards into a single page.

The changelog says:
> **Split & flip cards updated**
> Split and flip cards have been updated. Each half of the card has been combined into a single page.
> …
> **API Changes for Split/Flip Cards**
> Each split and flip card is now represented as a single object via the API instead of two. A new card_faces property has been added that contains information for each half of the split/flip card. See the updated API documentation for details.

I'm surprised these changes weren't done for double-face and meld cards, especially given that the property name is `card_faces`.

For meld cards, perhaps each "front" would represent its own card, such that Bruna//Brisela and Gisela//Brisela would each be a card.

**Comment by NilsEnevoldsen** [comment]
Oh, I didn't see this in the changelog. So this is probably a deliberate WONTFIX.

> Transform and meld cards are unaffected by this update. They will remain distinct cards with an `all_parts` field as usual.

**Comment by csuhta** [comment]
Merging transform/meld cards is a possible future change… maybe. 

The reason we didn't do it with this update is because requires adding support for having multiple images per card and—more annoyingly—correctly showing you the specific face of the card that you matched while searching. 

For example, if you search for `o:"control enchanted creature"` you would match [Soul Seizer](https://scryfall.com/card/dka/50a)//[Ghastly Haunting](https://scryfall.com/card/dka/50b) but we should show you the Ghastly Haunting side if you're using the image grid. Not sure how best to achieve that yet.

**Comment by NilsEnevoldsen** [comment]
Oh, excellent point.

**Comment by doppeldeveloper** [comment]
@csuhta I think the best approach would be to not alter the card data (e.g. don't add multiple images per card). Instead, alter only the page dedicated to displaying a card (i.e. the `scryfall/card/{set}/{id}` url):

Have that page check to see if it's showing a transform card. If it is, grab the *other* face to show that on the page as well. Have each show side-by-side with the "front" face on the left always, and have those cards show up in the same column view displayed in the site's narrowest breakpoint, i.e. have the stat block show up beneath the image.

A related possibility is issue #234 I just posted.

**Comment by gmac** [comment]
Oh, hey – this is done. https://scryfall.com/card/soi/49
