### ISSUE TITLE
Add image rotate/transform/meld buttons to appropriate cards

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#41]
Card images should be rotatable to see their text and artwork right-side-up:
 - [ ] Flip cards should have a rotate-180 button
 - [ ] Split and fuse cards should have a rotate-90 button (or be permanently rotated)
 - [ ] Aftermath cards should have a rotate-90 button
 - [ ] Plane cards should have a rotate-90 button (or be permanently rotated)

Additionally, if double-face cards and meld cards are combined into a single page (issue #40):
 - [ ] Double-face cards should have a transform button
 - [ ] Meld cards should have a meld/unmeld button

**Comment by gmac** [comment]
That's a good idea, I like it. I definitely agree that it's a pain to read upside-down and sideways card text on the screen.

**Comment by NilsEnevoldsen** [comment]
Thanks for listening to all the stuff I throw at you guys. I like Scryfall a lot.

**Comment by NilsEnevoldsen** [comment]
UI idea: this could be on:hover rather than a button.

**Comment by gmac** [comment]
We'd probably add in a button for it due to touch accessibility concerns (touch screens have no natural hover state).

**Comment by NilsEnevoldsen** [comment]
@gmac If you're replying by GitHub email – I had edited my comment to add "(on tap for mobile)". But yes, a button is also fine.

**Comment by gmac** [comment]
Rotation features are done. See https://scryfall.com/changelog/rotatable-images-for-split-cards-and-horizontal-layouts-122. 😱 

The flip effects are under review. If we don't formally release them, it's because they've been dropped due to technical or UX considerations.

Meld effects probably won't get a special treatment beyond the "related cards" menu that already exists. Alas, there's just no good way to represent half-card faces and their associated images in our database.
