### ISSUE TITLE
Syntax for accessing "print-level properties of other prints"

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#47]
I sometimes find myself wanting to apply print-level criteria (e.g. price, set/block/group, rarity, frame, artist, flavor text, is:online, is:promo) to other prints of that card.

For example:
 * What cards from Ravnica have promos?
 * What cards have been printed at both common and rare?
 * What cards were printed in Alpha, but not in Revised?
 * What Homelands cards have been printed online?
 * What Legends cards have been printed with a 2015 frame?
 * What cards have no prints under $20?
 * What cards with no prints under $20 aren't on the reserved list?

As far as I know, there's no way to execute these queries with current syntax – is there?

I'm not sure what such a syntax would look like. A suggestion shooting from the hip, using "anyprint/everyprint":
 * `is:promo (anyprint e:rav)`
 * `not:reserved (everyprint usd>20)`

**Comment by josephprice** [comment]
Screw that syntax, Niels. Challenge us to go full NLP and make Scryfall the Wolfram Alpha of Magic. =)

**Comment by csuhta** [comment]
There's actually an undocumented feature of `e:`, that uses a comma `e:lea,leb` to "find cards that have passed through `lea` and `leb`". You can substitute a `*` for one of the sets to make that half a no-op. We're working on a separate keyword for this confusing functionality.

So:

**What cards from Ravnica have promos?**

https://scryfall.com/search?q=%2B%2Bis%3Apromo+e%3A*%2Crav

**What cards were printed in Alpha, but not in Revised?**

https://scryfall.com/search?q=e%3Alea%2C*+-e%3Arev%2C*+e%3Alea

**What Homelands cards have been printed online?**

https://scryfall.com/search?q=%2B%2Be%3Ahml%2C*+is%3Aonline

**What Legends cards have been printed with a 2015 frame?**

https://scryfall.com/search?q=e%3Aleg%2C*+frame%3A2015

**What cards have been printed at both common and rare?**

You got me here, no operator can answer this question right now. What could it look like?

**What cards have no prints under $20?**
**What cards with no prints under $20 aren't on the reserved list?**

We can't answer this in satisfactory way, because we have incomplete price data. Many promos (and older cards not available for sale) do not have price information. Cards with no price information are filtered out entirely by price comparators. So if we had a way to search for this, you'd be filing a lot of inaccuracy tickets. 😉

**Comment by NilsEnevoldsen** [comment]
That's very cool, @csuhta. Thanks!

> `-e:rev,*`

Revised is `e:3ed` 😄

> `is:online`

I should file a ticket about this, actually. I want a keyword for any online set, rather than a special online set.

> What cards have been printed at both common and rare?
> You got me here, no operator can answer this question right now. What could it look like?

How about `r:c,r`?

**Comment by gmac** [comment]
It sounds like the original ticket has been satisfactorily answered, and subsequent inquiries have been opened separately. Closing this out.

**Comment by csuhta** [comment]
@NilsEnevoldsen https://scryfall.com/changelog/appeared-in-set-filter-84

**Comment by NilsEnevoldsen** [comment]
Fantastic, @csuhta. that takes care of 90% of my use cases.

Searching by other-print prices and rarity has come up, but not often.
