### ISSUE TITLE
search bar loses focus

### ISSUE THREAD

**Issue by tooomm** [scryfall/feedback#657]
>**Edit:
>The recommended, undocumented, feature with hitting <kbd>/</kbd> to focus the search bar does only work if your keyboard/language settings allow to access that character without any modifier keys!**

---

I checked a bunch of cards because I wanted to double check on their legality for certain formats...

In this process I realized that the search bar always loses focus after you submitted your request and the card shows up.
It would be very helpful if the search bar always keeps focus and you simply start typing after you had a look at a card! I can't think of any other reason one would want to type on your page except for entering something in the search bar.

**Comment by Sniffnoy** [comment]
Seconding this!

**Comment by silasary** [comment]
You can type `/` to focus the search bar.

Note that if the searchbar automatically took focus, navigating/scrolling via arrow keys or `hjkl` wouldn't work.

**Comment by Sniffnoy** [comment]
Huh, didn't know about "/", is that listed somewhere? Can't speak for the OP, but that's good enough for me!

**Comment by silasary** [comment]
I don't think any of the keyboard shortcuts are documented.  I discovered them entirely by accident/muscle memory.

**Comment by tooomm** [comment]
>You can type `/` to focus the search bar.

You misunderstood the problem here I guess.
1) on chromium that doesn't do anything
2) on firefox that opens the `Quick Search` of the browser to search on the displayed page

I'm speaking about the search bar from the scryfall page itself.

I might be totally wrong here, but how is that supposed to help if you are on [this page](https://scryfall.com/card/ima/65) for example and want to seach for card `Fireball` afterwards?

**Comment by silasary** [comment]
There's Javascript on the Scryfall page overrides the default browser behaviour.

If you're getting the default browser behaviour, I recommend checking whether you have Javascript disabled, or otherwise blocked from executing.

It works for me in Firefox, Chrome and Edge, so I'm inclined to assume you have NoScript installed?

**Comment by tooomm** [comment]
No idea what magic setup you use @silasary, but at least on Windows it doesn't do that for me. :)
And no, with Chromium I have no script blocker enabled and even disabled ad blocking for the test.
And with Firefox `scryfall.com` scripts are allowed. So that can't be it...

**Comment by csuhta** [comment]
So, we're not specifically looking to see if you typed a `/` character, instead we're using a keybind library that is checking if you pressed keycode `191`, which on about [50% of keyboards](https://support.apple.com/en-us/HT201794) is the key directly to the left of your <kbd>Shift</kbd> key. That's why it's not working on your German keyboard.

Do our keybinds for navigating search results <kbd>H</kbd><kbd>I</kbd><kbd>J</kbd><kbd>K</kbd> work correctly for you?

I've noticed that GitHub's own keyboard shortcuts use mostly the letter keys, so maybe it was unwise of us to bind an event to a punctuation key. Perhaps we could also bind focusing the search box to <kbd>F</kbd> as well?

**Comment by csuhta** [comment]
You can now type <kbd>F</kbd> in addition to the <kbd>/</kbd> key to focus the search box.

**Comment by tooomm** [comment]
@csuhta This does not work on the main page by the way. (but great change!)
