### ISSUE TITLE
Typo in RIX card text - Reckless Rage

### ISSUE THREAD

**Issue by JayDi85** [scryfall/feedback#676]
[Reckless Rage](https://scryfall.com/card/rix/110) have typo in ability text - wrong "dals" word instead "deals":

> Reckless Rage dals 4 damage to target creature you don’t control and 2 damage to target creature you control.

![shot_180106_230704](https://user-images.githubusercontent.com/8344157/34643011-6051958c-f336-11e7-9986-f64482f5265f.png)

**Comment by tooomm** [comment]
It looks like they care less about the feedback since they don't use it for the automatic tracking anymore. You should use the `Report card issue` at the bottom of the card page.
I'm sure it'll be fixed up in a blast. That's my experience at least so far...

Try entering your mail, maybe they'll let you know once the issue has been fixed!
