### ISSUE TITLE
Unhinged card duplicates shown for `e:unh`

### ISSUE THREAD

**Issue by ancestral** [scryfall/feedback#694]
https://scryfall.com/sets/unh?order=color

When searching for `e:unh` it shows duplicates, usually the foil. I see 168 cards, but there are only 140 in the set.

In some rare cases, there are some minor art differences between the foil and the not-foil, but unlike Unstable, there are no functional differences. Seeing the same card twice is not terribly helpful.

Can you filter out the duplicate foil cards in the results for set searches for `UNH`?

**Comment by NilsEnevoldsen** [comment]
Additionally, https://scryfall.com/search?q=b:unh+is:promo returns no results. I think the Unhinged promos should be in PUNH instead of UNH?

**Comment by csuhta** [comment]
These are in the correct set. Unhinged had alternate-watermark and alt-foil effects for foil rares. A similar Easter egg was included in [Planeshift (alternate art for story legends)](https://scryfall.com/search?q=%2B%2Be%3Apls+t%3Alegendary+-nemata) and [10E ("pro" foils) without reminder text](https://scryfall.com/search?q=%2B%2Be%3A10e+r%3Arare). They are not promo cards, as they were open-able in boosters. Because the cards are not identical when foiled, we count them as separate/secret prints.

**Comment by ancestral** [comment]
When searching for cards, I don’t think most people are interested seeing alternate prints. We have foils, promos, and alts visible in the card page. I feel that this really should be the same for Unhinged. There are only 140 unique cards, not 168.
