### ISSUE TITLE
Colorless tokens and emblems with incorrect color identity

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#785]
This is a very narrow issue, I admit, but I _think_ emblems have color identity…?

- [x] https://scryfall.com/card/tm15/12 (should be R)
- [x] ~https://scryfall.com/card/tc14/35 (should be B)~
- [x] ~https://scryfall.com/card/tm14/12 (should be B)~

**Comment by csuhta** [comment]
- Emblems specifically have no characteristics, even color (rule 113.1)
- I'll give you Land Mine, since it's a token. I think tokens technically have no color identity because they aren't deck cards or commanders, but we usually set the token's color identity equal to its colors for search convenience

**Comment by NilsEnevoldsen** [comment]
I thought emblems were permanents. Whoops.

Yes, the only reason I remotely cared about this is so that these things aren't surprises in various odd searches. Looks like you're correct that color identity is a property of a card, and tokens aren't cards.

Thanks!
