### ISSUE TITLE
Sorting by name handles spaces improperly

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#820]
https://scryfall.com/search?q=chandra+s:kld+not:pwdeck&as=checklist&order=name

Result:

№ | NAME | M.COST | TYPE | SET | R | ARTIST | USD | EUR | TIX
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
111 | Chandra's Pyrohelix | {1}{R} | Instant | KLD | C | Kieran Yanner | $0.05 | €0.04 | 0.01
110 | Chandra, Torch of Defiance | {2}{R}{R} | Legendary Planeswalker | KLD | M | Magali Ville… | $18.28 | €20.73 | 17.35

Expected:

№ | NAME | M.COST | TYPE | SET | R | ARTIST | USD | EUR | TIX
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
110 | Chandra, Torch of Defiance | {2}{R}{R} | Legendary Planeswalker | KLD | M | Magali Ville… | $18.28 | €20.73 | 17.35
111 | Chandra's Pyrohelix | {1}{R} | Instant | KLD | C | Kieran Yanner | $0.05 | €0.04 | 0.01

**Comment by csuhta** [comment]
This is not something we're going to be able to fix. Our database collation performs sorting based on the code value of letters. In this case `U+0027 ' APOSTROPHE` comes before `U+002C , COMMA`. WotC likely makes some manual "card catalog" adjustments to sorting in sets so that it's more pleasing to view in order.
