### ISSUE TITLE
Add MTG Arena IDs to the API

### ISSUE THREAD

**Issue by Fugiman** [scryfall/feedback#823]
The API currently returns the MTGO id for each card, it'd be great if it also returned the Arena ID.

**Comment by csuhta** [comment]
During the Arena beta, we have observed at least one major refactoring of the data files that Arena uses locally, which has made us weary of trying to build anything stable around it.

If you or someone else want to do the lifting and compile all of the Arena IDs, we would import it. (With the assumption that it might break with any Arena update in the future)

The best format would be a CSV or Google Sheet that maps Scryfall IDs to Arena IDs. If not, the second best would be a sheet that maps Arena IDs to card names, set codes, and collector numbers.

**Comment by shawkinsl** [comment]
Howdy y'all! I've managed to scrape all the arena card ID's for [mtgatracker](https://github.com/shawkinsl/mtga-tracker), and even have a .... er, [_mostly_ accurate way of verifying them automatically](https://github.com/shawkinsl/mtga-tracker/blob/master/app/set_data/test_set_data.py) (this particular file is messy, since I have to update it every time a big client change breaks something, so I don't recommend running [or reading] it). Anyways, I also anecdotally agree that some card ID's seem to be changing every once in a while. To be honest, the organization of ID's in general is a bit of a mess right now, so I wouldn't be surprised if they completely wiped them and started over in some big internal refactor along the way.

Anyways, if you are interested in getting a headstart with the current ID's, the current mapping is available for the current sets (in python, but easily exported to csv or json or whatever in a few lines) here: https://github.com/shawkinsl/mtga-tracker/blob/master/app/set_data/akh.py . The best way to get at these programatically, for export or whatever else is probably like this:

```
(venv) Spencatro@LAPTOP-2K3EQNOB ~/mtgatracker_example
λ cd mtga-tracker/
(venv) Spencatro@LAPTOP-2K3EQNOB ~/mtgatracker_example/mtga-tracker (master)
λ ipython
In [1]: import util
In [2]: for card in util.akh.Amonkhet.cards_in_set:
   ...:     print("{}: {}".format(card.mtga_id, card.pretty_name))
Out [2]:
65187: Ahn-Crop Champion
65033: Ahn-Crop Crasher
# ... etc
```

**Comment by shawkinsl** [comment]
Oh, right, I also stuck something on npm, but do not profess to be a node or js developer, so ymmv :P https://www.npmjs.com/package/mtga?activeTab=readme

**Comment by Fugiman** [comment]
[It Is Done](https://gist.github.com/Fugiman/e2c3a13d847fff47e27e545e3d58a3b6)

**Comment by csuhta** [comment]
@Fugiman In this list, you have two IDs for the double-sided cards. Is the higher ID the one for the backside?

**Comment by csuhta** [comment]
@Fugiman Also, Oath of the Gatewatch is not available on Arena. Did you mean to bind the IDs of these lands to the Amonkhet version?

**Comment by Fugiman** [comment]
No, I pulled the data for the cards directly from arena ([script](https://gist.github.com/Fugiman/e2c3a13d847fff47e27e545e3d58a3b6#file-arena_card_downloader-py) [json](https://gist.github.com/Fugiman/e2c3a13d847fff47e27e545e3d58a3b6#file-arena_cards_raw-json)) so according to that it really is Oath of the Gatewatch. Maybe the IDs just aren't used?

Yes, the higher ID is for the back face for double sided cards. For split cards the first ID is used during deck building and is the whole card, the second is the first half by itself and the third is the second half by itself (during games it appears as two seperate cards).

**Comment by shawkinsl** [comment]
Early in closed beta, they used OGW dual lands. I think you can still find them in the deck builder if you trick it. (Don't ask me why they did this.)

**Comment by shawkinsl** [comment]
@Fugiman how did you find that CDN?! This is awesome! (did you find any other goodies in there?)

**Comment by csuhta** [comment]
Can you actually obtain the OGW cards still? If not, I'll probably exclude them

**Comment by shawkinsl** [comment]
@csuhta yes, you can: 
![image](https://user-images.githubusercontent.com/1424566/40884108-7c0dad38-66c2-11e8-980b-0e72297d08cc.png)

**Comment by shawkinsl** [comment]
Oh, actually, yes they are collectible (idk why you'd do this, but you can spend a WC to make it): 
![image](https://user-images.githubusercontent.com/1424566/40884132-2d628572-66c3-11e8-82aa-96bddd9bf27e.png)

**Comment by csuhta** [comment]
Arena IDs are now available via the API and you can fetch cards by Arena ID on a unique endpoint:

https://scryfall.com/docs/api/cards/arena

If there are problems with individual cards, please use the "Report Card Issue" link on that card's page on Scryfall so we can triage them.

**Comment by Fugiman** [comment]
@csuhta Apologies for reviving this issue, but I figured it'd be easier to give you a new dump rather than reporting all the cards in kaladesh & aether revolt. Here's the updated list, with the same issues you found earlier as I haven't changed the download mechanism.

[cards.zip](https://github.com/scryfall/feedback/files/2082863/cards.zip)

**Comment by csuhta** [comment]
@Fugiman 

Done! https://api.scryfall.com/cards/arena/64273?pretty=true

It's totally fine to make new issues or reply to this one if you have new bulk data. We just want individual card reports if there's like less than 20 card issues or something.
