### ISSUE TITLE
Split is:digital and is:online into distinct modes

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#89]
When searching for cards that are online (eg: `o:monarch is:online`), Scryfall returns all cards that match the criteria and have been printed online (eg: PZ2 cards)

When searching `o:monarch not:online`, scryfall returns all cards that are not *exclusively* online. (eg: All cards from CN2, including ones reprinted in PZ2).

What I expect is for the search to return all cards from CN2 that *haven't* been printed in an online set.

To take it to the extreme:  `is:online -not:online` should just return Gleemox.  Instead, it returns all cards printed in an online-only set.

**Comment by csuhta** [comment]
Combining #49 into this thread.

We should change these operators such that:

- `is:digital` — Returns digital prints
- `is:online` — True for an Oracle card name if you can obtain it on MTGO somehow

**Comment by Sniffnoy** [comment]
Hello, just wanted to say that I'm glad this is being worked on, because adding the equivalent of the new is:online is something I was going to ask for as well!  Thank you all!  Hope you once again don't mind positive feedback in here. :)

**Comment by chuckharmston** [comment]
Update on this:

Since Scryfall effectively does/will support 4 different games with some overlap, we're going to revamp this a bit with a new `game:` operator that supports four values: `paper`, `mtgo`, `duels` (long-term goal to get Duels data and images), and `arena` (which I suspect we will support from day one).

This will be an attribute on _printings_, which I believe addresses the concerns outlined above.

**Comment by NilsEnevoldsen** [comment]
That sounds good to me. I assume those are indicators for availability in (rather than "print is exclusive to") that game.

What's the plan for `is:digital` and `is:online`? I kinda lean towards removing them because I suspect most people misunderstand them, but not quite all functionality of `is:online` (which would have been per-card) would be replaced by `game:`. (`is:digital` would be the same as `game:mtgo -game:paper` or perhaps `(game:mtgo or game:duels or game:arena) -game:paper` if I understand correctly.)

**Comment by Sniffnoy** [comment]
Having those be an attribute on printings and not having analogous searches for cards is something of a problem, actually, for the negated versions.  Say I want to do a search not:online to find all cards that haven't appeared on MTGO.  If you only have printing-based attributes there's no way to do that.

**Comment by NilsEnevoldsen** [comment]
@Sniffnoy Negated searches is much less of an edge case than my example. Good call.

**Comment by csuhta** [comment]
The attributes will be specific to individual prints (rather than Oracle names). We're keeping `is:digital` to mean "this is a virtual-only print", separate from the games. 

It should work out to let you see which individual prints you can obtain in each environment. Here are some examples:

| Card | `g:paper` | `g:mtgo` | `g:arena` | `g:duels` | `is:digital` |
| ---- | -- | -- | -- | --- | -- |
| [Gishath, Sun's Avatar (XLN)](https://scryfall.com/card/xln/222) | ✓ | ✓ | ✓ | | |
| [Gishath, Sun's Avatar (PXLN)](https://scryfall.com/card/pxln/222) | ✓ |  |  | | |
| [Force of Will (EMA)](https://scryfall.com/card/ema/49) | ✓ | ✓  |  | |  |
| [Force of Will (MED)](https://scryfall.com/card/med/33) |  | ✓  |  | | ✓ |

**Comment by csuhta** [comment]
If you're trying to determine if you cannot obtain a card at all on MTGO, it would be a search like `Sewers of Estark -game:mtgo`

**Comment by Sniffnoy** [comment]
That's still not sufficient for making a list of all cards that have never appeared online.  That is an actual search that I am actually interested in, that truly requires searching based on Oracle name and not based on printing.

Indeed even your Sewers of Estark example doesn't really work.  Let's consider -- say we search "[name] -g:mtgo", where [name] is some card name.  What are the possibilities that come up?

If the card has appeared on MTGO... it will still come up (unless the card you searched was Gleemox).  If the card hasn't appeared on MTGO... it will come up.  Yes if you click on the card and inspect the printings you can see whether it's appeared on MTGO or not, but you could do that already without the g:mtgo operator.  And for searches for multiple cards -- say, around 800 cards, because I believe that's the approximate number of cards that have never been printed on MTGO -- it's no good.

If you want to check what cards haven't appeared in a particular medium, you need card-based, not printing-based, attributes for it.

Thought: You already have card-based attributes for printings in the form of the "in:" operators.  Like you have the printing-based "e:plc" and the card-based "in:plc".  Perhaps that syntax could be extended to this case?  Like "g:mtgo" for online printings, and "in:mtgo" for cards that have appeared online?  Then you could find all the ones that haven't appeared online by searching "-in:mtgo".

**Comment by NilsEnevoldsen** [comment]
1. What happens to `is:online`? Does it remain a synonym of `is:digital`?
2. I still don't like the syntax `is:digital`. I'll stop griping about it, but I really think it's confusing syntax.

**Comment by csuhta** [comment]
- :new: https://www.patreon.com/posts/new-search-for-15133432
- `is:digital` is still around, it's essentially an alias for `-game:paper (game:mtgo or game:arena)`
- `is:online` has been retired.
